version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  redis_url_shortener:
    image: redis:alpine
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/var/lib/redis
      - $PWD/redis/:/usr/local/etc/redis/
    restart: always
    environment:
     - REDIS_REPLICATION_MODE=master
    container_name: url_shortener_redis

  db_url_shortener:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    container_name: url_shortener_db

  url_shortener:
    depends_on:
      - redis_url_shortener
      - db_url_shortener
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/var/www
    restart: always
    ports: 
      - "9000:80"
    environment:
      VIRTUAL_HOST: urlshortener.develop,www.urlshortener.develop
    container_name: url_shortener
volumes:
  db_data:
  redis_data:

networks:
  default:
    external:
      name: nginx-proxy
